### ISSUE TITLE
You cannot call a method on a null-valued expression.

### ISSUE THREAD

**Issue by ScottinOkla** [JellyKid/NinitePS#1]
I get the following error when using ver 1.0.0 of your script:

PS C:\Windows\Tools> .\niniteps.ps1 -audit -machine IT-MeyerS-PC
/audit /silent . /remote IT-MEYERS-PC
You cannot call a method on a null-valued expression.
At C:\Windows\Tools\NinitePs.ps1:381 char:55
-         if ($ComputerStats -and $ComputerStats.Name.Contains <<<< ($NewCompOb
  j.Name)) {
  - CategoryInfo          : InvalidOperation: (Contains:String) [], RuntimeE
    xception
  - FullyQualifiedErrorId : InvokeMethodOnNull

I get the following error when using the latest version of your script:

PS C:\Windows\Tools> .\niniteps.ps1 -audit -machine IT-MeyerS-PC
/audit /silent . /remote IT-MEYERS-PC
You cannot call a method on a null-valued expression.
At C:\Windows\Tools\NinitePs.ps1:424 char:55
-         if ($ComputerStats -and $ComputerStats.Name.Contains <<<< ($NewCompOb
  j.Name)) {
  - CategoryInfo          : InvalidOperation: (Contains:String) [], RuntimeE
    xception
  - FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by JellyKid** [comment]
I would make sure that you are on the latest version of powershell and are using ninitepro.exe and that it's in the same directory as the script. Also this script only works in an AD environment where you can look up computers with "Get-ADComputer -Filter {(cn -eq $Machine)}" and the machine must be in DNS. Make sure you can do an nslookup on IT-MeyerS-PC.
